---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA1B4iGH1ZTqrI4qE1QwtR8N8K3YbspSYjbTutHnKyRrj0WuzvouW85RHhl84xhhldPxvEzaoKzLk37T0RLEr7lzBIje34E3AOsOjJac/4i5CIWm9dGTrfBzE5RRFnfBnQfB47npFP6B4VO2IvpeIE2ZMr0Y87mOOjf+UBwoiOkb8wivIkxZU8AKvIBicmXWuXcxU5Me1Hz6FVYYSRDcessqNY+8ErOahBxF9e9WHdmNbruO0KP2VZCx3GwuLlMsSUEHPl95wdzdjlVvlcm7NS4AzwJ0h5N+d342mz0o7uyXf3O878xunur1UuNikEyJM5r/6g7q1C7tlw5AosdRdlEzbhxYa64rMBLfvF+hx09oFkkmqLXyq9+gSnWrIejrHbl0dKU5HFwPHMq19MdiTDSu1Dynmh8I0e1doIgGPVuBG01NaFb7RCEEu3AEubiiTBPRv+fiDt4vcaw+zp6R+NV8aShOsMsffzfXOCr7qDdD31phxt/gBZKWh7zoNIdS0rpi4pJfsr4QkfgccJHBfJ/DufMCOtXorzazTcQABe0TqNGERO6WO2KqBjFFmcT+lmBrAPfMx8YwJ9XWwAsnhAeQzre9vyySa/Lz0L5OP057zdtE5qWFlrNe8p1NORHp0NKOYCTK/pEXz4U0pXzIb65s4l5qdmqX44S85jyPDrPX5acr5JeD7sxp4je6lo9fk/2cB1j/afjAQmLm6Sb0tD4Na4JbZeH0HORT/pXpuT5bcY6Gwa8qrXGX81akZWdAZnfI0b1UQ==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
