---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgB2sYKoAbndaYVsWSTUiK4a3BUhvAAkcZVgyifiUEHP+iLq28LQEj7UnVgdGZb6zjTjpv1V2jFZz+/XG64j7qheGLs/ZJAAHNW80T2qndyk9U1TsOBSHJnMCoj0gqr8pqAZSbpCSBzM2ujCciWcU18RK/0hTabUY34SOX8EHgkjgbo8w1oZj9kp3DDjFYKv8NekhUlTXnZCb6OXD6ySMKbfiJq7mmQP6RMMa4q0JoaXq9w3V/qTKGI6yF+BdhX17WV3nTi2qhTX5BxI0c4RmlUzPZ4CSjMyRGzCZpVGlg6j6lvCZau2aWYYJgFHN85HYkFMNc2V1VQsCipPLeNLfCsoKW/8hfzRUV6fsIF4UUgUemsALNPf/MsGHxbtAwCQRANudDfPVXF/E6/yE2d/dBEa2tyoDTrzZpxyYxSXHIG3ClpyvkkMiU83/yzn/cQicHh5Et8GrpyWyUNPBQrkwgHfIlZOPEgSc+Bt+PT4yC6smhKk/wmiVjIw0ADTuo2KMXx2pkC3SXzGeXFbV4fHWVq6DPw7WUzqLM5TNo/gYavF7aBC+x9om+39msbAj6C6wB6wgdil5mBxDQeCWIQKa59N6t7raUXiwt13Rn8hmpgmz1YOd4wwEBkUw8b2aLc6XUGqLYSUPzJEetjdh0+SqZmqfwWhkcMnvtEcIL1Xr8Qt1/5qbj5mP+L0kmc8Mp7NeP4ZWPttY/Km7p6b6gPQVEyHiHLMkmzmkWdUEQXyrsMMC0kNbKZkJKD7DOS22m0hfhss/0T3hxQADkqruIDB9flnkOBlyWgCyUW1LRQTSAVfA64YGFXLUQy5YDTNHEbk6dXKEUGB1FTM7MEk1cjhDQRJWOJnFmQTF5APlHsKdS4ERaqCvZYoXOjsiUWnY09nCduozVmZ69Z3o1QBqB0+rrflm9Mvpk5BZEOBlj1yUH6r
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel
