---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBFPmvK3rzp+I12B1/MTXpNNmyW/CnglKQ8Mmfm0BcxcbZX4SRdV4GiMXMDzr1q0Cx/xnZqW3vvmelx5sKeHVkFCD/wll6JrghZneKNp/zm3P1WKQdjzmS171NGB6tbOotDtzioFCzHnfauj8dfro+dvGqQz9YdTzdyKcCMeVnVn52Dz2BW/CVtIZOeihK98VxUefVOmRkQJDkGYFeEE6h1EbjvGoaJXImH5YrkitVJfvbAmyd3QNEsZh6C9MQBcyb4hmHtHiNZK9EQ3t7AXvwzEBmPBgvrmK7WJT4+Enjd1N5oES3isk/83ln4nCJbJi1KE6iB9HePoA4QQI3k60bxTdswE5TnlsD8BKxIeExmn7GbqllHvi8Qct7ZkRMk/3WOogUA/Yco/RFqGmFPemCj3dzoGdwCqIRWVtTFKXDkbjJbSyo751dluZ20CCQGjlDN/qUUHER3VoehlIWIm17LjBrbeMN0C5YCbULWNsV5f6UCLl5tn1lwaP0dNT1SmjC8SMPy35UpqC22XA7RVEfXFkIMu+gUiL4VQyTgyLJDQ1vb0LpUlaMB1+DIiFRsczdio2VANWoIrJxWLWBp1R+0T3Z6E9+gNjNIiECp9uEkoba+JT357LAHuznU+LSNwmACY29Cmaz31fbzLLagaM5E4HgSriU5jIzmNNmDIdbjgTeyFAgEQM/cZJDY+sb4Acq1zqnChQxYTQD6vNo7WDasORIrL47V6ifMER2ToAvweIyTFhSnzusuSkRwgAfwtMRcaPAw0w==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
