---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgCXRDCslk5QaweLKyYhLbqlZ38+PlLWQXlWZNtFQdTABrNji/MDnfU5VJ2szSa9BvyCW3g8YXfN+Dg87xkPvOX8ckTNnzCbcBWvCXGjMCdWUdC8kwNkfPFFwMc1lMEoh0wivMe5EtDWqi3FpVXiD5Pk8qiFsHfXngdPDt1E8SKQABxWGGKb+UPpiq4zIaxaQstPqxtoNbQCD9wi03l5RYF2Sab/7x7TS5JuC/NfBIjrdPEmyQmJiFOMPxOGMz2fNz8ltVN2oyaZAGhy9Nz6tv8uvLZ0l+hbmQMfXe3cbzdFqhgHqG6L6VpGi3/WaQcYYbpxIxjAzJ4XDij9YbYMy9k+HtM4RJBBga4EqX43AakxGZp94cBrW1bKPw+tdu02HtN2OPVQtPBKUf47oQEuJVnpdv7WAYwLbR5W7Cyva/wsklblZI7N4lZaTEyqVE7Pg711Wfic9DqEJeNAL6S4NCnwYrAA8SP0lqzBzk+PB0NfeP8hjrj3enlzEh2Q4rk1AvrshlV+aEfQ/1NKtp3HQK0rzfb1C/2uh7/g79oysFTgvdmXDzpA7A8zrtP3acw+MvfnQgKunQghuUH1BzoW5fYiGCjgg8chUNvy8Mn2CwKPDSO3qlrXb9bpNEMOBRrWko3J8zgMI2iB7THody6JfuNGDtC7j3JCAXdS/j+CQDXjAFJEmDnaui32QY5ut8MNZ96CLfTkcJEceo/SZHUhX/8hy7xVXbO9Wb7iyXiS4CUpJqP38HLlHgiCccoa5qTNm982QJl+F0bq8YaSSQ8+NA5CZAuQ1CuU7TTPA1D7qWvpTVEvNX6BFLLygyd7FLIZw8BoioA10B17Mf5H9klfDa3JxywLR7LPmuIX+xXJVdhI2I0pcEPzcyhNmI64R+DFHPAkRS6hqZa6dQA83E8IvT3N037cGQwVGTXnZG6cOtBB
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel
