---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgBYa6CtjCefTxIH004Q7jCIjLUbitJI1R2+6Hnr/pS1skxDU3nSY5FpiOtmoKmSM5mq+7S6eMESphOjKMNxV5WDRKrfo/4T4f2YC0B0A+tuJ3pW/dMkO5upWhnJKJLLqlhWnrcRV4sp1apna6qbMQex7NBGuSWt6amrqdqjgqVl8Kaw50GlUIbIYw6gOrgO615xUNWuvWsfja0mkPS2fKWY96PXK/EfOr1N2RTcAOhSVX0kufC6QqkGF7/VF2ihkaILvDHzzWGbFMGfYIXYX/oURlPrryikjHsX2jGMFWircXR7io8R2eFsmy1d4bD3C+3l/pBIiJFC8gklQqcdjPDuVdotCH7oPMWCKfkfDj0hH0kuHvq1dRhtgfj1C2DKXs2w8rAbgxpQ0CKSL/o+yjO2p67CPqDv3wvLC/NNAsAYqWDgQHlkXSMeXD+Bpf+2yKcW2VkAKZC4sz4m8J9VhMTWfgYVPwFIyTvvnMiVjscnzjEpDmCYuOjcZC0flwA48CxRNABjHitnLGKdb6gArUgMfFkB5Mg+WwKXZDkOnURN8N0fydOqH9lhrZRYoqDOWbFRazSDeJHkX/0kN3OHAIlJATNV0ZqaEJjuA+NVBMtlRzf4gJm7kVR6hbLEMW2RHXeEC/z37jBvMhHmb3RO8xyi4WMM75G4Z+Byfm9y+0cvHryU+9B2BJnTEq+YUKJ9wfzSUdOpdCn0Y1dHjlrkZoauQEhYmQ8zjtnkqiMdmd3yq6ss+atbPOjx2MNzsTG7s+VEY4cfLw==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: external-dns
    type: Opaque
