---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgC8fTK6CuB5X6ivefH7IbFr5ItvD43JXQ7BxZ3ben8CGDebQdEcuGS5m02tfQQi34r4on4wAcK8Tb+xpt7Hezjj2/maopm/1bMw3DxCH1qF4yzfGjqXq4CDAioZtq8tf7pg+AJIN2KdqZ+JZgC4/yIp54VUxImvOtceh8P0OJQjUGm7P3mqy9BsxozTUU+VbM4o82poxpIc1cjsBz9eim5OvpIxy2yaul4JjaBuhuLBwGxw1dYms8MKwn9Wk2wz0eNRzCbsCTcLyob4nzhtz6iBTIUHKnAJUhLAFYhAK+5tMLiBdLvR5I+x5a3HQ7qNvk9i0HhZ3NTyeYHrf+W3H0kgfiX78WrAlRj3xqQWFT7w5GUkWNxBZeYghxjrmspumSfxl10h0wOc9Dwrga1Yt6Ou+nPg3R0QtEuUGzmV/oJaM4vUPpR2qonesjervgBzHBTwaukewLhd4bL2Xa93Eti1oQdkKjPuc1fubbpCXxHLWPR5BNW2DYUAj8i+nv/8XFpneYOcAGvN4RcMK7r6HRVqWcorwxwnpZJRfGKToegb229MwIdN8QfFKLxfSQauluATdS+FVwd489mINMssYQhTrz3UbaJXoujg2FFRKcSbIaRJZr57GH/Hs/Y1dacGl95f3eFMA0IQItGEe/u68mJth/jMiFGZDxwS6RHSv5JY38xqfq83Fd+A4f4qOJ0JMftDRc+N5DpXIHiles3JoMMhdyCqbj4qXIITZSdJB+rJ3jZ+ufyOAXV9GeJvilq219JmK8+FGy6tD/X6Ca99M+H2fLUuTxxF8LOYDVtQnHvc4q6eJf1ZpzXsVEgUKGqbS4i+J3OsfOVolEPKFdA6aEXAnJgqbjA5QUhgEmyl8W6gqieY3RcjZGdauvPMQuweFqlHhZy0oo7vhSmDYiP8kOgFZA9gYSKgqngBFFRf06uO
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel
