---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgAwP6cXeHBo9FLMfDLPy55Q32NRCo/aQHomXTzTeeSL6xlKF2tFl/UY1QQZgq543NuYRxUoXH3zAfTpMZqQ+5VfnYP7SUvcJeW+B0SBQvTheAEKRTEWkZuWa/5pk/U3Db9OdvVb4Khm8GENRoKe95kw529AQowPlONAYrGTt2qlGlGGedbLBVEYsljqySCB+wFEIazLmxz4BNvyS4lL/v2viyiF5/VsFp1oQ0HiLBco07WqkuXQOwzWav5lfHd0NpDc7WzZdach3T07mt+D2bS2iFxDbPF1Fa7WUfrllaJLCgaDYSI6xmlYW2+kCNBaDJRSC97OYBizWXa12CEH6yrJjrO/NJFYPZMdMJn2MPeIU6sf1aQ9dwSW5EeoE8mQFtjNlclgqR6mnl5/1ss1X2OTXBm2lsUW+i6yzo6icOLPQdOt1V+n/p5gix5XbhXetTfE1oHxSIfJjXLEA5gJH9M837L69TLJDfcmxzR4DcFZGkLclkA9SycYgKwRqlCCbdPyoSPjOjpE/Wg0+pjrxkh2xw+oXjyzeoC79DaT0d3Dsjfdi81tM1IOQe2X7dPkwm5lR7oQm9NJDV/SnIbfozulZCzDBLEB8hLPyvjcp/Py6lcrGOL7F9J0WOIYwofTeuJDC+7vRrj4OCSyJSsM7V9fAStz2dBrEjGspj7YtNOkTSULd1ViIQn3+jExyqaMqrkaOgoMtVDpe++Aa1FOy36PCeMwY15V4HILqJV5S4XPjkX5DlhdfVJBkwEGejKoQAcjSH29HQ==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: external-dns
