---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: external-dns
spec:
  encryptedData:
    cloudflare-api-token: AgAPkmGxAT+eHNimYhuOr4C94YcgRR+s62j2IgNpZLu1TJ894B0TVp07BLfhDmUsrzAj+Zp/KJOwTB5UhrMVRz+QL8QWIh7d/sq2ECQrE2l2xcMwILGyLFCO7/ynlWmPE5h7js6xkcL1sNSKU91+TVHivcHudJMACEm6DScrwUqQhHQc54C6nDO2kASUg9oXs/yzpEgwTRpp35QeJXYa2s1qavZmD6l0ZWB3dIm3K98knJ1BWrJtCFUvolzhSpIazybnBGeTuzX+vEjAjV3F9CZwjs14ZbCcKYYS9HPa6B0Fi1yX90k/M47nIZGKIfd2A8REhld9q619qvy7esBI9lgAFBEbPIXEff9D+PFQy+owCC6+vqCIuI3N5i8F3PpgJlkr6hziHbgDShQ0C2qy84UHPSKolrSyqlQknj2epSua13pA4RnvXP2nea8ttqdcoPXOszcZGibpUGUx5AQkSnkxvGNZpmL9aIyU+wbu1BgjKRPdiYqWXhbOaS/OYZ8dB7+9jJwRnkNhOjvpXZPkwD3Fzm590tSm7ulrLtuy0A1PZXxqWDrX7CE+yV+MbOA14KeexuDtLo5oscPgwZ/UlQOrYzXJFFGSP4xNDfq49jLOcKRrDy8f4ub9tVYrEAx6kPxCAO42yuXx+YCq2PHhUuO9MGUvnD5GRkuT9h0RTIqp1vM8qBMTbtpMNACfYdw0J7foAXm84k2Gtsg1moIFbumZMwi0LyeZ+bE69uGGogvWyhdsQGn2j3kYHiNZw8/I54PJ5hTFqQ==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: external-dns
