site_name: Infrastructure Lab Docs
site_description: from bare metal to cloud.

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: teal
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:
  - Home: index.md
  - Phase 1 — Local:
      - Admin Box: phase1/admin-box.md
      - ADR-001 Hardening Script: phase1/adr-001-hardening-script.md
  - Phase 2 — Cloud:
      - Network Architecture: phase2/network.md
      - ClickOps Deployment: phase2/aws-clickops-deployment.md
  - Phase 3 — Containerization:
      - CI/CD Pipeline: phase3/containerization.md
      - ADR-004 Workload Architecture: phase3/adr-004-workload-architecture.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
