apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
