apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-aws
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.19.0
    helm:
      releaseName: external-dns-aws
      values: |
        provider:
          name: cloudflare
        cloudflare:
          proxied: false
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token-secret
                key: api-token
        domainFilters:
          - northlift.net
        policy: sync
        registry: txt
        txtOwnerId: "aws-eks-prod"
        txtPrefix: "_edns_aws."
        sources:
          - ingress
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 150m
            memory: 256Mi
  destination:
    name: aws-eks-prod
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
