prometheus:
  prometheusSpec:
    retention: 3d
    scrapeInterval: 60s
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    resources:
      requests: { memory: 512Mi, cpu: 100m }
      limits:   { memory: 1Gi, cpu: 300m }

grafana:
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 150m
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        memory: 32Mi
        cpu: 20m
      limits:
        memory: 64Mi
        cpu: 50m

kubeStateMetrics:
  resources:
    requests:
      memory: 32Mi
      cpu: 20m
    limits:
      memory: 64Mi
      cpu: 50m

nodeExporter:
  resources:
    requests:
      memory: 16Mi
      cpu: 10m
    limits:
      memory: 32Mi
      cpu: 30m
